[tool.poetry]
name = "ai-agents-service"
version = "0.1.0"
description = "AI agents service"
authors = []
readme = "README.md"
packages = [{ include = "ai_agents" }]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "*"
langchain-core = "*"
langchain-openai = "*"
openai = "^2.30.0"
python-dotenv = "*"
google-genai = "^1.70.0"
pillow = "^12.2.0"
httpx = "^0.28.1"
langgraph = "^1.1.6"
litellm = "^1.83.4"
langfuse = "^2.0"
nest-asyncio = "*"
crawl4ai = "^0.8.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
